
import os
import errno

print(os.strerror(errno.EIO))


